#!/usr/bin/env python3
# Generate inline stub overrides for every IDirect3DDevice9 / IDirect3DDevice9Ex
# method, EXCEPT the ones the v2 driver implements for real. The output is meant
# to be #included inside the D9MTDevice class body, making the class concrete
# without hand-writing ~130 benign stubs. This is the "mass stub" the triangle
# milestone needs: unimplemented entry points return a harmless success/notimpl
# so a real app can call them without crashing.
import re
import sys

HEADER = sys.argv[1]
OUT = sys.argv[2]
# argv[3]: comma-separated interface names (base first, then derived)
# argv[4]: comma-separated method names we implement for real (no stub emitted)
INTERFACES = sys.argv[3].split(",") if len(sys.argv) > 3 else \
    ["IDirect3DDevice9", "IDirect3DDevice9Ex"]
IMPLEMENTED = set(sys.argv[4].split(",")) if len(sys.argv) > 4 else {
    "QueryInterface", "AddRef", "Release",
    "TestCooperativeLevel", "Reset",
    "Clear", "BeginScene", "EndScene", "SetFVF", "DrawPrimitiveUP", "Present",
}

text = open(HEADER).read()

def interface_body(name):
    # Grab from the interface declaration to the matching "};".
    start = text.find("DECLARE_INTERFACE_IID_(%s," % name)
    if start < 0:
        start = text.find("DECLARE_INTERFACE_(%s," % name)
    if start < 0:
        raise SystemExit("interface %s not found" % name)
    end = text.find("};", start)
    return text[start:end]

# Derived interface inherits the base; emit base methods first, then derived.
bodies = "\n".join(interface_body(n) for n in INTERFACES)

# Join wrapped STDMETHOD declarations into single lines terminated by PURE;
# Two macro forms: STDMETHOD(Name)(args) -> HRESULT, and
# STDMETHOD_(RetType, Name)(args) -> RetType.
flat = re.sub(r"\s+", " ", bodies)
decls = re.findall(r"STDMETHOD(?:_\([^)]*\)|\([^)]*\))\s*\([^;]*?\)\s*PURE\s*;", flat)

seen = set()
lines = []
for d in decls:
    m = re.match(
        r"STDMETHOD(?:_\(\s*([^,]+?)\s*,\s*([A-Za-z0-9_]+)\s*\)|\(\s*([A-Za-z0-9_]+)\s*\))"
        r"\s*\((.*)\)\s*PURE\s*;", d)
    if not m:
        continue
    ret = (m.group(1) or "HRESULT").strip()
    name = (m.group(2) or m.group(3)).strip()
    args = m.group(4).strip()
    if name in IMPLEMENTED or name in seen:
        continue
    seen.add(name)
    # THIS_ precedes the first real arg; THIS means no args.
    args = args.replace("THIS_", "").replace("THIS", "").strip()
    if args == "":
        params = ""
    else:
        params = args
    if ret == "HRESULT":
        body = "return D3DERR_NOTAVAILABLE;"
    elif ret in ("ULONG", "DWORD", "UINT", "int"):
        body = "return 0;"
    elif ret == "void" or ret == "VOID":
        body = ""
    else:
        # opaque return types (e.g. float, HRESULT-likes) — zero-init
        body = "return {};"
    lines.append("  %s STDMETHODCALLTYPE %s(%s) override { %s }" % (ret, name, params, body))

with open(OUT, "w") as f:
    f.write("// GENERATED by v2/scripts/gen_device_stubs.py — do not edit.\n")
    f.write("// Inline stub overrides for the IDirect3DDevice9Ex methods the v2\n")
    f.write("// triangle driver does not implement. #include inside the class body.\n")
    f.write("\n".join(lines))
    f.write("\n")

print("emitted %d stub methods -> %s" % (len(lines), OUT))
